language: node_js
node_js:
- "12"
install:
  - npm install
services:
  - postgresql
env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database book_a_meal;' -U postgres
  - npm run build
  - npm install -g sequelize-cli

script:
  - npm test
after_success:
  - npm run coveralls
